name: app-deploy

on:
  push:
    branches: [ main ]

env:
  DOMAIN: ckdemo.a1ck.io
  REGISTRY_PROJECT: demo
  TAG: v1

jobs:
  app-deploy:
    name: Deploy user-demo
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup KUBECONFIG
      env:
        KUBECONFIG_CONTENTS_B64: ${{ secrets.KUBECONFIG_CONTENTS_B64 }}
      run: |-
        mkdir -p ~/.kube
        echo $KUBECONFIG_CONTENTS_B64 | base64 -d > ~/.kube/config
        chmod 0400 ~/.kube/config

    - name: Deploy
      working-directory: user-demo
      run: |-
        helm upgrade \
            --install \
            myapp \
            deploy/ck8s-user-demo/ \
            --set image.repository=harbor.$DOMAIN/$REGISTRY_PROJECT/ck8s-user-demo \
            --set image.tag=$TAG \
            --set ingress.hostname=demo.$DOMAIN
